services:
  - type: web
    name: fastapi-product-api
    env: python
    region: virginia
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    autoDeploy: true