services:
  - type: web
    name: fastapi-product-api
    env: python
    region: virginia
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn main:app -k uvicorn.workers.UvicornWorker --workers 1 --bind 0.0.0.0:$PORT --timeout 120"
    plan: free
    autoDeploy: true